#  # Redis安装
  redis:
    image: redis:${REDIS6_VERSION}
    container_name: redis
    ports:
      - "${REDIS6_HOST_PORT}:6379"
    volumes:
      - ${REDIS6_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: [ "redis-server", "/etc/redis.conf" ]
    labels:
      "type": "redis"
    environment:
      TZ: "$TZ"
    networks:
      - default