  #phpmyadmin:
    image: phpmyadmin
    container_name: xii-phpmyadmin
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    volumes:
      - ${PHPMYADMIN_USER_CONF_FILE}:/etc/phpmyadmin/config.user.inc.php:ro
      - ${PHPMYADMIN_PHP_CONF_FILE}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini:ro
    networks:
      - default
    labels:
      "type": "phpmyadmin"
    environment:
      - PMA_HOST=mysql80
      - PMA_PORT=3306
      #      - PMA_ARBITRARY=1
      - TZ=$TZ