name: build
on:
  release:
    types: [released] #预发布时出发
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Run build script
        run: |
          chmod +x .github/scripts/build.sh
          ./.github/scripts/build.sh
        shell: bash
